language: node_js
os: linux
dist: trusty

node_js:
   - "10"
   - "12"
   - "14"
   - "15"
   - "16"
   - "17"
#   - "18" Disabled due to travis-ci error during nvm initialization: The command "npm config set spin false" failed and exited with 1 during .

services:
   - rabbitmq

script: npm run travis
